#!/bin/bash
# AmazingTeam E2E: Report Generator
# Generates combined test reports in multiple formats

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(dirname "$SCRIPT_DIR")"
REPORTS_DIR="$E2E_DIR/reports"
LOCAL_REPORTS="$E2E_DIR/local/reports"

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
DATE_ISO=$(date -Iseconds)

TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
SKIPPED_TESTS=0

TEST_RESULTS="[]"

mkdir -p "$REPORTS_DIR" "$LOCAL_REPORTS"

process_report() {
    local report_file="$1"
    
    if [ -f "$report_file" ]; then
        local status=$(cat "$report_file" | grep -o '"status"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | grep -o '"[^"]*"$' | tr -d '"')
        local test_id=$(cat "$report_file" | grep -o '"test_id"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | grep -o '"[^"]*"$' | tr -d '"')
        local test_name=$(cat "$report_file" | grep -o '"test_name"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | grep -o '"[^"]*"$' | tr -d '"')
        local duration=$(cat "$report_file" | grep -o '"duration_seconds"[[:space:]]*:[[:space:]]*[0-9]*' | head -1 | grep -o '[0-9]*$')
        
        if [ -z "$duration" ]; then
            duration="0"
        fi
        
        TOTAL_TESTS=$((TOTAL_TESTS + 1))
        
        case "$status" in
            pass)
                PASSED_TESTS=$((PASSED_TESTS + 1))
                ;;
            fail)
                FAILED_TESTS=$((FAILED_TESTS + 1))
                ;;
            skip)
                SKIPPED_TESTS=$((SKIPPED_TESTS + 1))
                ;;
        esac
        
        TEST_RESULTS=$(echo "$TEST_RESULTS" | jq --arg id "$test_id" --arg name "$test_name" --arg status "$status" --arg dur "$duration" \
            '. + [{"test_id": $id, "test_name": $name, "status": $status, "duration_seconds": ($dur | tonumber)}]')
    fi
}

for report in "$REPORTS_DIR"/test-*.json; do
    if [ -f "$report" ]; then
        process_report "$report"
    fi
done

SUMMARY_MD="$LOCAL_REPORTS/summary-$TIMESTAMP.md"
SUMMARY_JSON="$LOCAL_REPORTS/summary-$TIMESTAMP.json"
JUNIT_XML="$LOCAL_REPORTS/junit-$TIMESTAMP.xml"

cat > "$SUMMARY_MD" << EOF
# AmazingTeam E2E Test Report

**Generated**: $DATE_ISO
**Environment**: Local

---

## Test Results Summary

| Metric | Value |
|--------|-------|
| Total Tests | $TOTAL_TESTS |
| Passed | $PASSED_TESTS |
| Failed | $FAILED_TESTS |
| Skipped | $SKIPPED_TESTS |

EOF

if [ $FAILED_TESTS -eq 0 ]; then
    echo "**Result**: ✅ All tests passed" >> "$SUMMARY_MD"
else
    echo "**Result**: ❌ $FAILED_TESTS test(s) failed" >> "$SUMMARY_MD"
fi

cat >> "$SUMMARY_MD" << EOF

---

## Test Details

| Test | Status | Duration |
|------|--------|----------|
EOF

echo "$TEST_RESULTS" | jq -r '.[] | "| \(.test_name) | \(.status) | \(.duration_seconds)s |"' >> "$SUMMARY_MD"

cat >> "$SUMMARY_MD" << EOF

---

*Generated by AmazingTeam E2E Test System*
EOF

cat > "$SUMMARY_JSON" << EOF
{
  "report_version": "1.0.0",
  "generated_at": "$DATE_ISO",
  "environment": {
    "type": "local",
    "runner": "$(uname -s 2>/dev/null || echo 'unknown')",
    "node_version": "$(node --version 2>/dev/null || echo 'unknown')"
  },
  "summary": {
    "total": $TOTAL_TESTS,
    "passed": $PASSED_TESTS,
    "failed": $FAILED_TESTS,
    "skipped": $SKIPPED_TESTS
  },
  "tests": $TEST_RESULTS
}
EOF

cat > "$JUNIT_XML" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="AmazingTeam E2E Tests" tests="$TOTAL_TESTS" failures="$FAILED_TESTS" skipped="$SKIPPED_TESTS" timestamp="$DATE_ISO">
EOF

echo "$TEST_RESULTS" | jq -r '.[] | "  <testcase name=\"\(.test_name)\" classname=\"\(.test_id)\" time=\"\(.duration_seconds)\">\(.status == "fail" ? "<failure message=\"Test failed\"/>" : .status == "skip" ? "<skipped/>" : "")</testcase>"' >> "$JUNIT_XML"

echo "</testsuite>" >> "$JUNIT_XML"

ln -sf "$SUMMARY_MD" "$LOCAL_REPORTS/latest-summary.md" 2>/dev/null || cp "$SUMMARY_MD" "$LOCAL_REPORTS/latest-summary.md"

echo "Reports generated:"
echo "  - Markdown: $SUMMARY_MD"
echo "  - JSON: $SUMMARY_JSON"
echo "  - JUnit: $JUNIT_XML"
echo ""
echo "Summary: $PASSED_TESTS passed, $FAILED_TESTS failed, $SKIPPED_TESTS skipped"

if [ $FAILED_TESTS -gt 0 ]; then
    exit 1
fi

exit 0