/**
 * Init Command
 * Initialize AmazingTeam in a project
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const VERSION = require('../../package.json').version;

const COLORS = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  red: '\x1b[31m',
  cyan: '\x1b[36m'
};

function log(message, color = 'reset') {
  console.log(`${COLORS[color] || ''}${message}${COLORS.reset}`);
}

function createRL() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
}

function question(rl, prompt, defaultValue = null) {
  return new Promise(resolve => {
    const displayPrompt = defaultValue 
      ? `${prompt} (${defaultValue}): `
      : `${prompt}: `;
    rl.question(displayPrompt, answer => {
      resolve(answer || defaultValue);
    });
  });
}

function fileExists(filePath) {
  return fs.existsSync(filePath);
}

function getTemplate(name) {
  const templates = {
    'amazingteam.config.yaml': `# AmazingTeam Project Configuration
# Generated by amazingteam init

version: "1.0"

project:
  name: "{{PROJECT_NAME}}"
  description: "{{PROJECT_DESCRIPTION}}"
  language: "{{LANGUAGE}}"
  framework: "{{FRAMEWORK}}"

amazingteam:
  version: "{{AMAZINGTEAM_VERSION}}"
  # GitHub Action for CI/CD (change if using your own fork)
  github_action: "Burburton/amazingteam-action@v1"

workflow:
  commit_mode: "{{COMMIT_MODE}}"
  pr:
    auto_merge: false
    require_review: {{REQUIRE_REVIEW}}
    reviewers: []
  direct:
    require_ci_pass: true

build:
  command: "{{BUILD_COMMAND}}"
  test: "{{TEST_COMMAND}}"
  lint: "{{LINT_COMMAND}}"

# Uncomment to use an overlay:
# overlay: "{{OVERLAY}}"

# Custom rules (optional)
rules:
  test_coverage_threshold: 80
  max_function_lines: 30
`,

    'opencode.jsonc': `{
  "$schema": "https://opencode.ai/config.json",
  "instructions": ["AGENTS.md"],
  "autoupdate": true,
  "permission": {
    "edit": "ask",
    "bash": "ask"
  },
  "tools": {
    "write": true,
    "edit": true,
    "bash": true
  }
}
`,

    'gitignore_additions': `
# Node modules
node_modules/

# AI Team cache (downloaded by workflow)
.amazing-team-cache/

# AI Team local foundation (downloaded by \`amazingteam local\`)
.amazing-team-local/

# OpenCode config (auto-generated, can be regenerated)
# opencode.jsonc
`
  };
  
  return templates[name] || '';
}

function getWorkflowTemplate(githubAction, version) {
  return `# AmazingTeam GitHub Action Workflow
# This workflow enables AI-powered development in your repository

name: AmazingTeam

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  amazing-team:
    if: |
      startsWith(github.event.comment.body, '/ai') ||
      startsWith(github.event.comment.body, '/opencode') ||
      startsWith(github.event.comment.body, '/oc')
    
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: \${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.name "opencode-bot"
          git config --global user.email "opencode-bot@users.noreply.github.com"

      - name: Setup AmazingTeam
        uses: ${githubAction}
        with:
          version: '${version}'
          config: 'amazingteam.config.yaml'

      - name: Run OpenCode
        uses: anomalyco/opencode/github@latest
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`;
}

function getLanguageDefaults(language) {
  const defaults = {
    typescript: {
      framework: 'node',
      buildCommand: 'npm run build',
      testCommand: 'npm test',
      lintCommand: 'npm run lint'
    },
    javascript: {
      framework: 'node',
      buildCommand: 'npm run build',
      testCommand: 'npm test',
      lintCommand: 'npm run lint'
    },
    python: {
      framework: 'fastapi',
      buildCommand: 'python -m build',
      testCommand: 'pytest',
      lintCommand: 'ruff check .'
    },
    go: {
      framework: 'gin',
      buildCommand: 'go build ./...',
      testCommand: 'go test ./...',
      lintCommand: 'golangci-lint run'
    },
    java: {
      framework: 'spring',
      buildCommand: './mvnw package',
      testCommand: './mvnw test',
      lintCommand: './mvnw checkstyle:check'
    },
    cpp: {
      framework: 'qt',
      buildCommand: 'cmake --build build',
      testCommand: 'ctest --test-dir build',
      lintCommand: 'clang-tidy'
    },
    rust: {
      framework: 'cargo',
      buildCommand: 'cargo build',
      testCommand: 'cargo test',
      lintCommand: 'cargo clippy'
    }
  };
  
  return defaults[language] || defaults.typescript;
}

async function run(options, positional) {
  const rl = createRL();
  
  try {
    log('\n🚀 AmazingTeam Foundation Initializer\n', 'cyan');
    
    const projectPath = process.cwd();
    const projectName = positional[0] || path.basename(projectPath);
    
    // Check if already initialized
    const configPath = path.join(projectPath, 'amazingteam.config.yaml');
    if (fileExists(configPath) && !options.force) {
      log('⚠️  AmazingTeam already initialized in this directory.', 'yellow');
      log('   Use --force to reinitialize.\n');
      rl.close();
      return;
    }
    
    // Interactive prompts or use options
    let language = options.language;
    let framework = options.framework;
    let description = options.description;
    let overlay = options.overlay;
    
    if (!options.language) {
      language = await question(rl, 'Language', 'typescript');
    }
    
    if (!options.framework) {
      const defaultFramework = getLanguageDefaults(language).framework;
      framework = await question(rl, 'Framework', defaultFramework);
    }
    
    if (!options.description) {
      description = await question(rl, 'Description', 'My awesome project');
    }
    
    if (!options.overlay && options.overlay !== null) {
      const overlayAnswer = await question(rl, 'Overlay (leave empty for none)', '');
      overlay = overlayAnswer || null;
    }
    
    // Workflow Configuration
    log('\n⚙️  Workflow Configuration\n', 'cyan');
    
    let commitMode = options.commitMode;
    let requireReview = options.requireReview;
    let githubAction = options.githubAction || 'Burburton/amazingteam-action@v1';
    
    if (!options.commitMode) {
      console.log('  Commit modes:');
      console.log('    pr     - Create Pull Request, wait for human review (safer, recommended)');
      console.log('    direct - Commit directly to branch (faster, less oversight)');
      const modeAnswer = await question(rl, 'Commit mode (pr/direct)', 'pr');
      commitMode = modeAnswer.toLowerCase() === 'direct' ? 'direct' : 'pr';
    }
    
    if (commitMode === 'pr' && options.requireReview === undefined) {
      const reviewAnswer = await question(rl, 'Require human review before merge? (y/n)', 'y');
      requireReview = reviewAnswer.toLowerCase() !== 'n';
    }
    
    if (!options.githubAction) {
      console.log('\n  GitHub Action for CI/CD:');
      console.log('    Default: Burburton/amazingteam-action@v1');
      console.log('    Change this only if using your own fork');
      const actionAnswer = await question(rl, 'GitHub Action', 'Burburton/amazingteam-action@v1');
      githubAction = actionAnswer || 'Burburton/amazingteam-action@v1';
    }
    
    const langDefaults = getLanguageDefaults(language);
    
    log('\n📦 Creating project structure...', 'blue');
    
    // Create directories
    const dirs = [
      '.amazing-team/memory/planner',
      '.amazing-team/memory/architect',
      '.amazing-team/memory/developer',
      '.amazing-team/memory/qa',
      '.amazing-team/memory/reviewer',
      '.amazing-team/memory/triage',
      '.amazing-team/memory/ci-analyst',
      '.amazing-team/memory/failures',
      '.github/workflows',
      'tasks/_template',
      'src'
    ];
    
    for (const dir of dirs) {
      const fullPath = path.join(projectPath, dir);
      if (!fileExists(fullPath)) {
        fs.mkdirSync(fullPath, { recursive: true });
      }
    }
    
    log('📝 Creating configuration files...', 'blue');
    
    // Generate amazingteam.config.yaml
    let configContent = getTemplate('amazingteam.config.yaml');
    const baseUrlSection = llmBaseUrl 
      ? `\n  base_url: "${llmBaseUrl}"` 
      : '';
    configContent = configContent
      .replace(/\{\{PROJECT_NAME\}\}/g, projectName)
      .replace(/\{\{PROJECT_DESCRIPTION\}\}/g, description)
      .replace(/\{\{LANGUAGE\}\}/g, language)
      .replace(/\{\{FRAMEWORK\}\}/g, framework)
      .replace(/\{\{AMAZINGTEAM_VERSION\}\}/g, VERSION)
      .replace(/\{\{COMMIT_MODE\}\}/g, commitMode)
      .replace(/\{\{REQUIRE_REVIEW\}\}/g, requireReview ? 'true' : 'false')
      .replace(/\{\{BUILD_COMMAND\}\}/g, langDefaults.buildCommand)
      .replace(/\{\{TEST_COMMAND\}\}/g, langDefaults.testCommand)
      .replace(/\{\{LINT_COMMAND\}\}/g, langDefaults.lintCommand)
      .replace(/\{\{OVERLAY\}\}/g, overlay || '');
    
    fs.writeFileSync(configPath, configContent);
    
    // Generate opencode.jsonc
    const opencodeContent = getTemplate('opencode.jsonc');
    const opencodePath = path.join(projectPath, 'opencode.jsonc');
    fs.writeFileSync(opencodePath, opencodeContent);
    
    // Generate workflow
    const workflowPath = path.join(projectPath, '.github', 'workflows', 'amazingteam.yml');
    fs.writeFileSync(workflowPath, getWorkflowTemplate(githubAction, VERSION));
    
    // Update .gitignore
    log('📝 Updating .gitignore...', 'blue');
    const gitignorePath = path.join(projectPath, '.gitignore');
    let gitignoreContent = '';
    
    if (fileExists(gitignorePath)) {
      gitignoreContent = fs.readFileSync(gitignorePath, 'utf-8');
      if (!gitignoreContent.includes('.amazing-team-local/')) {
        gitignoreContent += getTemplate('gitignore_additions');
        fs.writeFileSync(gitignorePath, gitignoreContent);
      }
    } else {
      fs.writeFileSync(gitignorePath, getTemplate('gitignore_additions').trim() + '\n');
    }
    
    // Create placeholder memory files
    log('📋 Creating memory placeholders...', 'blue');
    const memoryFiles = {
      'planner': ['decomposition_notes.md', 'flow_rules.md'],
      'architect': ['architecture_notes.md', 'module_map.md'],
      'developer': ['implementation_notes.md', 'bug_investigation.md'],
      'qa': ['test_strategy.md', 'validation_notes.md'],
      'reviewer': ['review_notes.md', 'quality_rules.md'],
      'triage': ['classification_heuristics.md', 'debug_notes.md'],
      'ci-analyst': ['failure_patterns.md', 'runbook_references.md'],
      'failures': ['failure_library.md']
    };
    
    for (const [role, files] of Object.entries(memoryFiles)) {
      for (const file of files) {
        const filePath = path.join(projectPath, '.amazing-team', 'memory', role, file);
        if (!fileExists(filePath)) {
          fs.writeFileSync(filePath, `# ${role} ${file.replace('.md', '').replace(/_/g, ' ')}\n\n`);
        }
      }
    }
    
    // Create task template
    const taskTemplatePath = path.join(projectPath, 'tasks', '_template', 'task.yaml');
    if (!fileExists(taskTemplatePath)) {
      fs.writeFileSync(taskTemplatePath, `id: template
title: Task Title
type: feature
status: backlog
priority: medium
owner_role: developer
depends_on: []
blocked_by: []
acceptance_criteria: []
risk_level: low
module_scope: []
`);
    }
    
    log('\n✅ AmazingTeam initialized successfully!\n', 'green');
    
    log('Next steps:', 'cyan');
    log('  1. Run OpenCode in this directory:');
    log('     opencode');
    log('  2. Configure your LLM provider:');
    log('     /connect    - Add API credentials');
    log('     /models     - Select a model');
    log('  3. Review amazingteam.config.yaml');
    log('  4. Create your first issue!\n');
    
    log('Configuration:', 'cyan');
    log(`  Project: ${projectName}`);
    log(`  Language: ${language}`);
    log(`  Framework: ${framework}`);
    log(`  Version: ${VERSION}`);
    if (overlay) {
      log(`  Overlay: ${overlay}`);
    }
    log('');
    
  } finally {
    rl.close();
  }
}

function help() {
  return `
${COLORS.cyan}amazingteam init${COLORS.reset} - Initialize AmazingTeam in a project

${COLORS.yellow}Usage:${COLORS.reset}
  amazingteam init [project-name] [options]

${COLORS.yellow}Options:${COLORS.reset}
  --language, -l <lang>    Programming language (default: typescript)
  --framework <fw>         Framework (default: based on language)
  --overlay, -o <name>     Apply overlay (python-backend, web-fullstack, etc.)
  --description, -d <desc> Project description
  --commit-mode <mode>     Commit mode: pr or direct (default: pr)
  --force                  Force reinitialization

${COLORS.yellow}Examples:${COLORS.reset}
  amazingteam init                              Interactive initialization
  amazingteam init my-project                   Create project with defaults
  amazingteam init -l python -o python-backend  Python with overlay
  amazingteam init --force                      Reinitialize existing project

${COLORS.yellow}Created Files:${COLORS.reset}
  amazingteam.config.yaml      Project configuration
  opencode.jsonc               OpenCode configuration (customize with /connect and /models)
  .github/workflows/amazingteam.yml   GitHub Action workflow
  .amazing-team/memory/        Role memory directories
  tasks/_template/             Task template directory

${COLORS.yellow}Next Steps:${COLORS.reset}
  1. Run 'opencode' in the project directory
  2. Use /connect to configure your LLM provider
  3. Use /models to select your model
`;
}

module.exports = { run, help };