#!/bin/bash
# AmazingTeam E2E Test: Local Test Runner
# Runs all basic tests and generates combined report

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(dirname "$SCRIPT_DIR")"
REPORTS_DIR="$E2E_DIR/local/reports"
LOG_DIR="$E2E_DIR/logs"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_section() { echo -e "\n${BLUE}=== $1 ===${NC}\n"; }

SCOPE="${1:-basic}"
START_TIME=$(date +%s)

mkdir -p "$REPORTS_DIR" "$LOG_DIR"

REPORT_FILE="$REPORTS_DIR/summary-$(date +%Y%m%d-%H%M%S).md"

cat > "$REPORT_FILE" << EOF
# AmazingTeam E2E Test Report

**Generated**: $(date)
**Scope**: $SCOPE
**Environment**: Local

---

## Test Results

EOF

TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0

run_test() {
    local test_script="$1"
    local test_name="$2"
    
    TOTAL_TESTS=$((TOTAL_TESTS + 1))
    
    echo "" >> "$REPORT_FILE"
    echo "### $test_name" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    
    log_info "Running: $test_name"
    
    if bash "$test_script"; then
        PASSED_TESTS=$((PASSED_TESTS + 1))
        echo "| Status | ✅ PASS |" >> "$REPORT_FILE"
        log_info "✅ $test_name PASSED"
    else
        FAILED_TESTS=$((FAILED_TESTS + 1))
        echo "| Status | ❌ FAIL |" >> "$REPORT_FILE"
        log_error "❌ $test_name FAILED"
    fi
}

log_section "AmazingTeam E2E Tests"
log_info "Scope: $SCOPE"
log_info "Report: $REPORT_FILE"
echo ""

if [[ "$SCOPE" == "basic" || "$SCOPE" == "all" ]]; then
    log_section "Basic Tests"
    
    run_test "$E2E_DIR/scripts/test-install.sh" "NPM Install"
    run_test "$E2E_DIR/scripts/test-init.sh" "CLI Initialization"
    run_test "$E2E_DIR/scripts/test-config.sh" "Config Validation"
fi

if [[ "$SCOPE" == "all" ]]; then
    log_section "Additional Tests"
    
    run_test "$E2E_DIR/scripts/test-skills.sh" "Skills Loading"
    
    if [ -n "$AMAZINGTEAM_API_KEY" ]; then
        run_test "$E2E_DIR/scripts/test-agent.sh" "Agent Response"
    else
        log_warn "Skipping Agent test (AMAZINGTEAM_API_KEY not set)"
        echo "### Agent Response" >> "$REPORT_FILE"
        echo "| Status | ⏭️ SKIP |" >> "$REPORT_FILE"
        echo "| Reason | AMAZINGTEAM_API_KEY not set |" >> "$REPORT_FILE"
    fi
fi

END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

cat >> "$REPORT_FILE" << EOF

---

## Summary

| Metric | Value |
|--------|-------|
| Total Tests | $TOTAL_TESTS |
| Passed | $PASSED_TESTS |
| Failed | $FAILED_TESTS |
| Duration | ${DURATION}s |

EOF

if [ $FAILED_TESTS -eq 0 ]; then
    echo "**Result**: ✅ All tests passed" >> "$REPORT_FILE"
else
    echo "**Result**: ❌ $FAILED_TESTS test(s) failed" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by AmazingTeam E2E Test System*" >> "$REPORT_FILE"

log_section "Test Complete"
log_info "Total: $TOTAL_TESTS | Passed: $PASSED_TESTS | Failed: $FAILED_TESTS | Duration: ${DURATION}s"
log_info "Report saved: $REPORT_FILE"

if [ $FAILED_TESTS -gt 0 ]; then
    log_error "Some tests failed. Check logs in: $LOG_DIR"
    exit 1
fi

exit 0